### PR TITLE
New workflow: Stale (auto close old Issues) + small fix

### PR DESCRIPTION
**Pull request by mkz212**

### CODE REVIEW

**Comment by mkz212** [comment]
@jandersonhill done, you can merge

**Comment by jandersonhill** [comment]
Thanks, this has been done. Let me know if there is anything else outstanding

**Comment by mkz212** [comment]
@jandersonhill Please add changelog! To 1.8.5 and 1.8.6. 

Changelog:

Refresh interval change. Recomended: 10 minutes. Minimum 1 minute, Maximum 360 minutes (6 hours). Note: More frequent refresh would result in too much daily number of requests to the Panasonic server, which could result in an account lock for 24 hours, or even a complete API lock.

**Comment by jandersonhill** [comment]
Do you want to keep this in a separate file as suggested by embee?

PS I thought we were going to add this to the workflow so that it asked for summary before publishing to npm?

**Comment by mkz212** [comment]
@jandersonhill Go to discord

**Pull request merged**
