### PR TITLE
Use Play Store rather than App Store to fetch latest version

### PR DESCRIPTION
**Pull request by nanos**
I propose to use the Google Play Store rather than the Apple Play store to detect the latest version.

This is because this is now hard coded to use the latest Play Store version and Client ID, so a mis-match with the Apple App Store is irrelevant.

### CODE REVIEW

**Comment by mkz212** [comment]
I like it but.. Maybe add separate function to check Google Play instead of changing this one? This may come in handy someday.

**Comment by nanos** [comment]
Yep:

```
Error:   121:11  error  'getAppStoreVersion' is assigned a value but never used  @typescript-eslint/no-unused-vars
```

Let me know what you want to do.

**Comment by mkz212** [comment]
one sec

**Comment by mkz212** [comment]
```
async configurePlugin() {
    this.log.info(`Plugin App version: ${APP_VERSION}.`);
    await this.getPlayStoreVersion();
    await this.getAppStoreVersion();
    await this.loginAndDiscoverDevices();
  }
```

please do not touch existing function (only change name of this function) and add new function before or after this function.

**Comment by nanos** [comment]
Can I ask why?

Don’t get me wrong, ultimately it’s your project and I’ll do it if you want to. 

However, my motivation for the change was that this was warning about the mismatch of versions on every startup. This confused me, as I assumed the plugin needed updating. 

However, it doesn’t need updating as it’s up to date with the latest play store version. 

As such I personally feel that checking the App Store is simply a waste, and pointing out a version mismatch actively confusing.

**Comment by mkz212** [comment]
> Can I ask why?
> 
> Don’t get me wrong, ultimately it’s your project and I’ll do it if you want to.
> 
> However, my motivation for the change was that this was warning about the mismatch of versions on every startup. This confused me, as I assumed the plugin needed updating.
> 
> However, it doesn’t need updating as it’s up to date with the latest play store version.
> 
> As such I personally feel that checking the App Store is simply a waste, and pointing out a version mismatch actively confusing.

so maybe in both function insted of just log.info the version add check- if version is different then log.info?

**Comment by nanos** [comment]
> so maybe in both function insted of just log.info the version add check- if version is different then log.info?

that’s mostly what they currently do: log.info the current version. Second log.info if there’s a mismatch (actually on play store it’s log.error as the assumption is that the old version will quickly stop version after an update, so this serves as early warning)

**Comment by mkz212** [comment]
hmm... ok! good idea! 👍 just comment app store function to silent lint error and i will merge 👍

**Comment by nanos** [comment]
Ok. Will do when I have a moment.

**Comment by mkz212** [comment]
Or maybe run getAppStoreVersion() in catch of getPlayStoreVersion? So if it cannot check from Google Play it will check from App Store?

**Comment by nanos** [comment]
> Or maybe call getAppStoreVersion() in catch of getPlayStoreVersion? So if it cannot check from Google Play it will check from App Store?

OK, implemented this one.

**Comment by mkz212** [comment]
Thank you! 👍👍👍

**Comment by mkz212** [comment]
@nanos I didn't find any errors or anything else to improve, so i think thak we can publish? Or you have something?

**Comment by nanos** [comment]
@mkz212 yeah, sounds good with me.

**Comment by mkz212** [comment]
> @mkz212 yeah, sounds good with me.

published. do you see update? cause for me it doesnt show up , and i dont have option "install other version" for this plugin (for other plugins i have)

**Comment by nanos** [comment]
Strangely not. 🤔

**Comment by mkz212** [comment]
> Strangely not. 🤔

I have now published another beta version and also does not see the update. But on npm they are, both public and beta.

In log i have error: 

```
[homebridge-panasonic-ac-platform] Failed to check registry.npmjs.org for updates: "Cannot read properties of undefined (reading 'length')" - see https://homebridge.io/w/JJSz6 for help.
```

P.S: I invited you to maintain the repo.

**Comment by nanos** [comment]
Looks very much like an issue with the npm registry. Probably just a matter of waiting.

**Comment by mkz212** [comment]
> Looks very much like an issue with the npm registry. Probably just a matter of waiting.

But for all other plugins working ok... ?

**Comment by mkz212** [comment]
@nanos Ok. I know! Author of the plugin is '@embee8' . But for new version it shows '@jandersonhill' (he is also maintain repo), embee leave project.

**Comment by mkz212** [comment]
@nanos this is latest commit to config ui maybe this is problem? 

https://github.com/homebridge/homebridge-config-ui-x/commit/a7739b76175806a0604b3ac67a69dfaeaded6e55

**Comment by mkz212** [comment]
@nanos You can check here this error: https://github.com/homebridge/homebridge-config-ui-x/blob/a7739b76175806a0604b3ac67a69dfaeaded6e55/src/modules/plugins/plugins.service.ts#L1281

**Comment by nanos** [comment]
I find it hard to imagine. But you could always had a `"maintainers": []` to the package.json a tag 4.0.1. Maybe it’ll help?

**Comment by nanos** [comment]
@mkz212 if I read the code correctly, and if that’s the source of the error (which I still doubt) then it can’t be a beta release but must be a full one.

**Comment by nanos** [comment]
@mkz212 you were right: that fixed it. 

image

**Comment by mkz212** [comment]
> @mkz212 you were right: that fixed it.
> 
> image

👍 But i dont install any homebridge ui update so why this changed? And why other plugins work ok and they dont have mainteiners [] in package? This is realy strange!

**Comment by mkz212** [comment]
Oh.. Here is explanation:  https://github.com/homebridge/homebridge-config-ui-x/pull/2069

**Comment by nanos** [comment]
lol. That’s the npm registry for you. Classic…

**Comment by mkz212** [comment]
I now published 4.0.2 and it appeared in "Install other version" but the update notification did not pop up. 

In 4.0.2 I corrected the mainteners from "@embee8" to "embee" because "@" is hardcoded in homebridge ui and it was doubled.

When i restart homebridge notification shows up but author name in plugin card was corrected before update. 

As if after restarting homebridge, the author was get from the latest release on npm and not from the current installed one.

Is it the same for you?

**Comment by embee8** [comment]
Could you please remove my handle from the list of maintainers? Reason: I don't maintain the project.

The people who currently commit code and lead the direction of development should be listed as maintainers. Why not list yourself, @mkz212?

**Comment by nanos** [comment]
> I now published 4.0.2 and it appeared in "Install other version" but the update notification did not pop up.

latest version info is cached in Homebridge for a bit. The cache is cleared in restart. So that would explain it. 

I did get the update notification without restart as I waited long enough for the cache to clear on its own.

**Comment by mkz212** [comment]
> Could you please remove my handle from the list of maintainers? Reason: I don't maintain the project.
> 
> The people who currently commit code and lead the direction of development should be listed as maintainers. Why not list yourself, @mkz212?

Ok, changed! 👍

**Pull request merged**
