### PR TITLE
Merge 1.8.0

### PR DESCRIPTION
**Pull request by embee8**
## Description

- Choice of what the Oscilate switch controls: swing, nanoe, eco navi, inside cleaning.
- Choice what value should be at each AC change (called from Homekit) for: swing, nanoe, eco navi, inside cleaning.
- When the internal unit does not have a temperature sensor, the temperature of the external unit is display, and when there are no both, it is automatically depending on the mode (heating / cooling).

Committing this work on behalf of @mkz212, hence not signing responsible for the checklist below.

## Type of change

- [ ] Documentation or repository updates
- [ ] Bug fix: non-breaking change which fixes an issue (patch version)
- [x] New feature: non-breaking change which adds functionality (minor version)
- [ ] Breaking change: fix or feature that would cause existing functionality to not work as expected (major version)

## Checklist

- [ ] I have read and comply with the [contributing guidelines](https://github.com/homebridge-panasonic-ac-platform/homebridge-panasonic-ac-platform/blob/master/CONTRIBUTING.md).
- [ ] I have tested my code for new features & regressions on my local installation, using the latest version of Homebridge.
- [ ] I have made corresponding changes to the documentation (README.md and plugin settings descriptions).

### CODE REVIEW

**Comment by embee8** [comment]
@mkz212, @jandersonhill, please review and let me know whether all looks good.

**Comment by mkz212** [comment]
@embee8 I will check when I return home approx. 15:00. Thank you very much for such a commitment to help us and the development of the plugin! In fact, a lot of work! 👍

**Comment by mkz212** [comment]
@embee8 For me everything ok! 👍

One thing I want to mark regarding this function with setting the value (nanoe, eco navi, swing, inside cleaning) when starting AC. Apple Home even after changing Rotation Speed sends also command On. So, we will either leave it as it is and it will be values set at startup and actually every AC setting change in Apple Home? Or we will add some "if device is turned off" to this function? What do you think? I think that if someone sets that he wants to have such a value, that always.

If you agree with me can you swap in config.schema.json `Swing value on every activation: do nothing, set on, set off.` to something like: `Swing value on every AC change in Homekit (turning on, change mode, rotation speed etc.): do nothing, set on, set off.`and analogously for the others (nanoe, eco navi and inside cleaning) ?

**Comment by embee8** [comment]
I haven't followed any of the conversations on the respective Issues and hence don't have an opinion on these points.

Best to discuss such topics in Issues with users who have such systems, ideally before the PR is submitted and a release is on its way out. While beta releases can be helpful to get feedback on the latest changes, they shouldn't become a public test environment.

On the topic of HomeKit: I recommend to not try to override its default behaviors. This is an Apple Home integration after all, and the art always lies in staying close to its architecture while bridging the gap into the Panasonic Comfort Cloud world.

**Comment by embee8** [comment]
Will need a summary of the changes before I merge it.

@mkz212, can you write 2-3 sentences on what this PR is introducing?

**Comment by mkz212** [comment]
New functions:

- Choice of what to control Oscilate Switch: swing, nanoe, eco navi, inside cleaning.
- Choice what value should be at each AC change (called from Homekit) for: swing, nanoe, eco navi, inside cleaning.
- When the internal unit does not have a temperature sensor, the temperature of the external unit is display, and when there are no both, it is automatically depending on the mode (heating / cooling).

**Pull request merged**
