### PR TITLE
Use Cookie Jar

### PR DESCRIPTION
**Pull request by nanos**
Use cookie jar to maintain session
Also deals with relative/absolute location headers.

I can now get all the way through to step 6 (getting a new token by `POST`ing to `https://accsmart.panasonic.com/auth/v2/login`) where I'm blocked by CloudFront:

```html
<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n <HTML>

<HEAD>
    <META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n<TITLE>ERROR: The request could not be
        satisfied</TITLE>\n</HEAD>

<BODY>\n<H1>403 ERROR</H1>\n<H2>The request could not be satisfied.</H2>\n
    <HR noshade size=\"1px\">\nRequest blocked.\nWe can't connect to the server for this app or website at this time.
    There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.\n<BR
        clear=\"all\">\nIf you provide content to customers through CloudFront, you can find steps to troubleshoot and
    help prevent this error by reviewing the CloudFront documentation.\n<BR clear=\"all\">\n
    <HR noshade size=\"1px\">\n
    <PRE>\nGenerated by cloudfront (CloudFront)\nRequest ID: [redacted]\n</PRE>
    \n<ADDRESS>\n</ADDRESS>\n</BODY>

</HTML>
```

### CODE REVIEW

**Comment by mkz212** [comment]
Panasonic blocks IP if there are too many errone queries. But I don't know if that's it.

**Comment by mkz212** [comment]
@nanos You need to fix some errors in PR.

**Comment by nanos** [comment]
> Panasonic blocks IP if there are too many errone queries. But I don't know if that's it.

Let's hope that's it, and that it'll just work after a while!

**Comment by nanos** [comment]
> @nanos You need to fix some errors in PR.

done

**Comment by mkz212** [comment]
Tkanks. Beta.18 released. I will test when back home.

**Comment by mkz212** [comment]
Zrzut ekranu 2024-06-21 o 10 03 17

cannot read what step is this cause log is very long

**Comment by mkz212** [comment]
@nanos I also stuck in step 6.

**Pull request merged**
